### ISSUE TITLE
Wallet disconnect 

### ISSUE THREAD

**Issue by lauridskern** [nftlabs/ui#47]
Hi,
what is the "disconnectWallet" hook supposed to do? 
It just opens metamask and wants to connect the wallet even if it already is connected.

**Comment by adam-maj** [comment]
> Hi, what is the "disconnectWallet" hook supposed to do? It just opens metamask and wants to connect the wallet even if it already is connected.

So this is an issue with the way metamask works - technically you can never actually disconnect, except through the metamask modal itself which is why it gets popped up. This is in fact the only way to do it - except on apps where it may _look_ like the metamask is being disconnected - but actually under the hood its still connected, they just show you otherwise.

That begin said, we're working on a better setup for this in the coming days/weeks.

Hope this answers your question :)
